class Autogenerated {
  int? success;
  String? message;
  int? currentRecord;
  List<Data>? data;

  Autogenerated({this.success, this.message, this.currentRecord, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    currentRecord = json['currentRecord'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = this.success;
    data['message'] = this.message;
    data['currentRecord'] = this.currentRecord;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int? artistId;
  String? artistName;
  String? smallImg;
  String? mediumImg;
  String? largeImg;
  String? slug;
  String? channelId;
  String? insertDt;
  int? maxViewCount; // Adjusted from Null? to int?

  Data({
    this.artistId,
    this.artistName,
    this.smallImg,
    this.mediumImg,
    this.largeImg,
    this.slug,
    this.channelId,
    this.insertDt,
    this.maxViewCount,
  });

  Data.fromJson(Map<String, dynamic> json) {
    artistId = json['artist_id'];
    artistName = json['artist_name'];
    smallImg = json['small_img'];
    mediumImg = json['medium_img'];
    largeImg = json['large_img'];
    slug = json['slug'];
    channelId = json['channel_id'];
    insertDt = json['insert_dt'];
    maxViewCount = json['max_view_count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['artist_id'] = this.artistId;
    data['artist_name'] = this.artistName;
    data['small_img'] = this.smallImg;
    data['medium_img'] = this.mediumImg;
    data['large_img'] = this.largeImg;
    data['slug'] = this.slug;
    data['channel_id'] = this.channelId;
    data['insert_dt'] = this.insertDt;
    data['max_view_count'] = this.maxViewCount;
    return data;
  }
}
