class Autogenerated {
  String? message;
  int? totalRecords;
  int? currentRecords;
  List<Data>? data;

  Autogenerated({
    this.message,
    this.totalRecords,
    this.currentRecords,
    this.data,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'] as String?;
    totalRecords = json['totalRecords'] as int?;
    currentRecords = json['currentRecords'] as int?;
    if (json['data'] != null) {
      data = List<Data>.from(json['data'].map((v) => Data.fromJson(v)));
    }
  }

  Map<String, dynamic> toJson() {
    return {
      'message': message,
      'totalRecords': totalRecords,
      'currentRecords': currentRecords,
      'data': data?.map((v) => v.toJson()).toList(),
    };
  }
}

class Data {
  int? videosFinalDataUniqueId;
  String? videosFinalDataUuid;
  int? artistId;
  String? artistName;
  String? artistSlug;
  String? videoTitle;
  String? videoDescription;
  String? videoLink;
  List<String>? videoTags;
  List<Categories>? categories;
  String? videoSmallImg;
  String? videoMediumImg;
  String? videoLargeImg;
  String? videoStandardImg;
  String? videoMaxresImg;
  String? videoSlug;
  String? videoPublishDate;
  String? videoLyrics; // Changed from Null to String?
  String? originalCredits; // Changed from Null to String?
  String? videoDuration;
  String? videoDefinition;
  String? videoCaption;
  String? status;
  String? createdByUuid; // Changed from Null to String?
  String? createdByName; // Changed from Null to String?
  String? modifiedByUuid; // Changed from Null to String?
  String? modifiedByName; // Changed from Null to String?
  String? createTs;

  Data({
    this.videosFinalDataUniqueId,
    this.videosFinalDataUuid,
    this.artistId,
    this.artistName,
    this.artistSlug,
    this.videoTitle,
    this.videoDescription,
    this.videoLink,
    this.videoTags,
    this.categories,
    this.videoSmallImg,
    this.videoMediumImg,
    this.videoLargeImg,
    this.videoStandardImg,
    this.videoMaxresImg,
    this.videoSlug,
    this.videoPublishDate,
    this.videoLyrics,
    this.originalCredits,
    this.videoDuration,
    this.videoDefinition,
    this.videoCaption,
    this.status,
    this.createdByUuid,
    this.createdByName,
    this.modifiedByUuid,
    this.modifiedByName,
    this.createTs,
  });

  Data.fromJson(Map<String, dynamic> json) {
    videosFinalDataUniqueId = json['videos_final_data_unique_id'] as int?;
    videosFinalDataUuid = json['videos_final_data_uuid'] as String?;
    artistId = json['artist_id'] as int?;
    artistName = json['artist_name'] as String?;
    artistSlug = json['artist_slug'] as String?;
    videoTitle = json['video_title'] as String?;
    videoDescription = json['video_description'] as String?;
    videoLink = json['video_link'] as String?;
    videoTags = List<String>.from(json['video_tags'] ?? []);
    if (json['categories'] != null) {
      categories = List<Categories>.from(
          json['categories'].map((v) => Categories.fromJson(v)));
    }
    videoSmallImg = json['video_small_img'] as String?;
    videoMediumImg = json['video_medium_img'] as String?;
    videoLargeImg = json['video_large_img'] as String?;
    videoStandardImg = json['video_standard_img'] as String?;
    videoMaxresImg = json['video_maxres_img'] as String?;
    videoSlug = json['video_slug'] as String?;
    videoPublishDate = json['video_publish_date'] as String?;
    videoLyrics = json['video_lyrics'] as String?;
    originalCredits = json['original_credits'] as String?;
    videoDuration = json['video_duration'] as String?;
    videoDefinition = json['video_definition'] as String?;
    videoCaption = json['video_caption'] as String?;
    status = json['status'] as String?;
    createdByUuid = json['created_by_uuid'] as String?;
    createdByName = json['created_by_name'] as String?;
    modifiedByUuid = json['modified_by_uuid'] as String?;
    modifiedByName = json['modified_by_name'] as String?;
    createTs = json['create_ts'] as String?;
  }

  Map<String, dynamic> toJson() {
    return {
      'videos_final_data_unique_id': videosFinalDataUniqueId,
      'videos_final_data_uuid': videosFinalDataUuid,
      'artist_id': artistId,
      'artist_name': artistName,
      'artist_slug': artistSlug,
      'video_title': videoTitle,
      'video_description': videoDescription,
      'video_link': videoLink,
      'video_tags': videoTags,
      'categories': categories?.map((v) => v.toJson()).toList(),
      'video_small_img': videoSmallImg,
      'video_medium_img': videoMediumImg,
      'video_large_img': videoLargeImg,
      'video_standard_img': videoStandardImg,
      'video_maxres_img': videoMaxresImg,
      'video_slug': videoSlug,
      'video_publish_date': videoPublishDate,
      'video_lyrics': videoLyrics,
      'original_credits': originalCredits,
      'video_duration': videoDuration,
      'video_definition': videoDefinition,
      'video_caption': videoCaption,
      'status': status,
      'created_by_uuid': createdByUuid,
      'created_by_name': createdByName,
      'modified_by_uuid': modifiedByUuid,
      'modified_by_name': modifiedByName,
      'create_ts': createTs,
    };
  }
}

class Categories {
  int? categoriesId;
  String? categoryName;
  String? categorySlug;

  var videoTitle;

  Categories({this.categoriesId, this.categoryName, this.categorySlug});

  Categories.fromJson(Map<String, dynamic> json) {
    categoriesId = json['categories_id'] as int?;
    categoryName = json['category_name'] as String?;
    categorySlug = json['category_slug'] as String?;
  }

  Map<String, dynamic> toJson() {
    return {
      'categories_id': categoriesId,
      'category_name': categoryName,
      'category_slug': categorySlug,
    };
  }
}
