class Autogenerated {
  int? success;
  String? message;
  int? totalRecord;
  int? currentRecord;
  Data? data;

  Autogenerated(
      {this.success,
      this.message,
      this.totalRecord,
      this.currentRecord,
      this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    totalRecord = json['totalRecord'];
    currentRecord = json['currentRecord'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['success'] = this.success;
    data['message'] = this.message;
    data['totalRecord'] = this.totalRecord;
    data['currentRecord'] = this.currentRecord;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  List<ArtistBio>? artistBio;
  List<dynamic>? artistDetails;
  List<Playlist>? playlist;

  Data({this.artistBio, this.artistDetails, this.playlist});

  Data.fromJson(Map<String, dynamic> json) {
    if (json['artistBio'] != null) {
      artistBio = <ArtistBio>[];
      json['artistBio'].forEach((v) {
        artistBio!.add(ArtistBio.fromJson(v));
      });
    }
    if (json['artistDetails'] != null) {
      artistDetails = <dynamic>[];
      json['artistDetails'].forEach((v) {
        artistDetails!.add(v);
      });
    }
    if (json['playlist'] != null) {
      playlist = <Playlist>[];
      json['playlist'].forEach((v) {
        playlist!.add(Playlist.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.artistBio != null) {
      data['artistBio'] = this.artistBio!.map((v) => v.toJson()).toList();
    }
    if (this.artistDetails != null) {
      data['artistDetails'] = this.artistDetails;
    }
    if (this.playlist != null) {
      data['playlist'] = this.playlist!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class ArtistBio {
  int? id;
  int? artistId;
  String? bio;
  String? smallImg;
  String? mediumImg;
  String? largeImg;
  String? xlargeImg;
  String? xxlargeImg;
  String? insertDt;
  String? artistName;

  ArtistBio(
      {this.id,
      this.artistId,
      this.bio,
      this.smallImg,
      this.mediumImg,
      this.largeImg,
      this.xlargeImg,
      this.xxlargeImg,
      this.insertDt,
      this.artistName});

  ArtistBio.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    artistId = json['artist_id'];
    bio = json['bio'];
    smallImg = json['small_img'];
    mediumImg = json['medium_img'];
    largeImg = json['large_img'];
    xlargeImg = json['xlarge_img'];
    xxlargeImg = json['xxlarge_img'];
    insertDt = json['insert_dt'];
    artistName = json['artist_name'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = this.id;
    data['artist_id'] = this.artistId;
    data['bio'] = this.bio;
    data['small_img'] = this.smallImg;
    data['medium_img'] = this.mediumImg;
    data['large_img'] = this.largeImg;
    data['xlarge_img'] = this.xlargeImg;
    data['xxlarge_img'] = this.xxlargeImg;
    data['insert_dt'] = this.insertDt;
    data['artist_name'] = this.artistName;
    return data;
  }
}

class Playlist {
  int? finalVideoPageId;
  String? artist;
  String? title;
  String? youtubeDescription;
  String? youtubeLink;
  String? youtubeTags;
  String? categories;
  String? smallImg;
  String? mediumImg;
  String? largeImg;
  String? standardImg;
  String? maxresImg;
  String? slug;
  String? youtubePublishDate;
  int? viewPageCount;
  int? youtubeViewCount;
  int? youtubeLikeCount;
  String? lyrics;
  String? originalCredits;
  String? artistSlug;
  String? viewCount;
  String? likeCount;
  String? favoriteCount;
  String? commentCount;
  String? duration;
  String? definition;
  String? caption;
  String? insertDt;

  Playlist(
      {this.finalVideoPageId,
      this.artist,
      this.title,
      this.youtubeDescription,
      this.youtubeLink,
      this.youtubeTags,
      this.categories,
      this.smallImg,
      this.mediumImg,
      this.largeImg,
      this.standardImg,
      this.maxresImg,
      this.slug,
      this.youtubePublishDate,
      this.viewPageCount,
      this.youtubeViewCount,
      this.youtubeLikeCount,
      this.lyrics,
      this.originalCredits,
      this.artistSlug,
      this.viewCount,
      this.likeCount,
      this.favoriteCount,
      this.commentCount,
      this.duration,
      this.definition,
      this.caption,
      this.insertDt});

  Playlist.fromJson(Map<String, dynamic> json) {
    finalVideoPageId = json['final_video_page_id'];
    artist = json['artist'];
    title = json['title'];
    youtubeDescription = json['youtube_description'];
    youtubeLink = json['youtube_link'];
    youtubeTags = json['youtube_tags'];
    categories = json['categories'];
    smallImg = json['small_img'];
    mediumImg = json['medium_img'];
    largeImg = json['large_img'];
    standardImg = json['standard_img'];
    maxresImg = json['maxres_img'];
    slug = json['slug'];
    youtubePublishDate = json['youtube_publish_date'];
    viewPageCount = json['view_page_count'];
    youtubeViewCount = json['youtube_view_count'];
    youtubeLikeCount = json['youtube_like_count'];
    lyrics = json['lyrics'];
    originalCredits = json['original_credits'];
    artistSlug = json['artist_slug'];
    viewCount = json['view_count'];
    likeCount = json['like_count'];
    favoriteCount = json['favorite_count'];
    commentCount = json['comment_count'];
    duration = json['duration'];
    definition = json['definition'];
    caption = json['caption'];
    insertDt = json['insert_dt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['final_video_page_id'] = this.finalVideoPageId;
    data['artist'] = this.artist;
    data['title'] = this.title;
    data['youtube_description'] = this.youtubeDescription;
    data['youtube_link'] = this.youtubeLink;
    data['youtube_tags'] = this.youtubeTags;
    data['categories'] = this.categories;
    data['small_img'] = this.smallImg;
    data['medium_img'] = this.mediumImg;
    data['large_img'] = this.largeImg;
    data['standard_img'] = this.standardImg;
    data['maxres_img'] = this.maxresImg;
    data['slug'] = this.slug;
    data['youtube_publish_date'] = this.youtubePublishDate;
    data['view_page_count'] = this.viewPageCount;
    data['youtube_view_count'] = this.youtubeViewCount;
    data['youtube_like_count'] = this.youtubeLikeCount;
    data['lyrics'] = this.lyrics;
    data['original_credits'] = this.originalCredits;
    data['artist_slug'] = this.artistSlug;
    data['view_count'] = this.viewCount;
    data['like_count'] = this.likeCount;
    data['favorite_count'] = this.favoriteCount;
    data['comment_count'] = this.commentCount;
    data['duration'] = this.duration;
    data['definition'] = this.definition;
    data['caption'] = this.caption;
    data['insert_dt'] = this.insertDt;
    return data;
  }
}
