class Autogenerated {
  int? success;
  String? message;
  int? totalRecord;
  int? currentRecord;
  List<Data>? data;

  Autogenerated({
    this.success,
    this.message,
    this.totalRecord,
    this.currentRecord,
    this.data,
  });

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    totalRecord = json['totalRecord'];
    currentRecord = json['currentRecord'];
    if (json['data'] != null) {
      data = (json['data'] as List).map((v) => Data.fromJson(v)).toList();
    } else {
      data = [];
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> dataMap = {};
    dataMap['success'] = success;
    dataMap['message'] = message;
    dataMap['totalRecord'] = totalRecord;
    dataMap['currentRecord'] = currentRecord;
    if (data != null) {
      dataMap['data'] = data!.map((v) => v.toJson()).toList();
    }
    return dataMap;
  }
}

class Data {
  int? finalVideoPageId;
  String? artist;
  String? title;
  String? youtubeDescription;
  String? youtubeLink;
  String? youtubeTags;
  String? categories;
  String? smallImg;
  String? mediumImg;
  String? largeImg;
  String? standardImg;
  String? maxresImg;
  String? slug;
  String? youtubePublishDate;
  int? viewPageCount;
  int? youtubeViewCount;
  int? youtubeLikeCount;
  String? lyrics;
  String? originalCredits;
  String? artistSlug;
  String? viewCount;
  String? likeCount;
  String? favoriteCount;
  String? commentCount;
  String? duration;
  String? definition;
  String? caption;
  String? insertDt;

  Data({
    this.finalVideoPageId,
    this.artist,
    this.title,
    this.youtubeDescription,
    this.youtubeLink,
    this.youtubeTags,
    this.categories,
    this.smallImg,
    this.mediumImg,
    this.largeImg,
    this.standardImg,
    this.maxresImg,
    this.slug,
    this.youtubePublishDate,
    this.viewPageCount,
    this.youtubeViewCount,
    this.youtubeLikeCount,
    this.lyrics,
    this.originalCredits,
    this.artistSlug,
    this.viewCount,
    this.likeCount,
    this.favoriteCount,
    this.commentCount,
    this.duration,
    this.definition,
    this.caption,
    this.insertDt,
  });

  Data.fromJson(Map<String, dynamic> json) {
    finalVideoPageId = json['final_video_page_id'];
    artist = json['artist'];
    title = json['title'];
    youtubeDescription = json['youtube_description'];
    youtubeLink = json['youtube_link'];
    youtubeTags = json['youtube_tags'];
    categories = json['categories'];
    smallImg = json['small_img'];
    mediumImg = json['medium_img'];
    largeImg = json['large_img'];
    standardImg = json['standard_img'];
    maxresImg = json['maxres_img'];
    slug = json['slug'];
    youtubePublishDate = json['youtube_publish_date'];
    viewPageCount = json['view_page_count'];
    youtubeViewCount = json['youtube_view_count'];
    youtubeLikeCount = json['youtube_like_count'];
    lyrics = json['lyrics'];
    originalCredits = json['original_credits'];
    artistSlug = json['artist_slug'];
    viewCount = json['view_count'];
    likeCount = json['like_count'];
    favoriteCount = json['favorite_count'];
    commentCount = json['comment_count'];
    duration = json['duration'];
    definition = json['definition'];
    caption = json['caption'];
    insertDt = json['insert_dt'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> dataMap = {};
    dataMap['final_video_page_id'] = finalVideoPageId;
    dataMap['artist'] = artist;
    dataMap['title'] = title;
    dataMap['youtube_description'] = youtubeDescription;
    dataMap['youtube_link'] = youtubeLink;
    dataMap['youtube_tags'] = youtubeTags;
    dataMap['categories'] = categories;
    dataMap['small_img'] = smallImg;
    dataMap['medium_img'] = mediumImg;
    dataMap['large_img'] = largeImg;
    dataMap['standard_img'] = standardImg;
    dataMap['maxres_img'] = maxresImg;
    dataMap['slug'] = slug;
    dataMap['youtube_publish_date'] = youtubePublishDate;
    dataMap['view_page_count'] = viewPageCount;
    dataMap['youtube_view_count'] = youtubeViewCount;
    dataMap['youtube_like_count'] = youtubeLikeCount;
    dataMap['lyrics'] = lyrics;
    dataMap['original_credits'] = originalCredits;
    dataMap['artist_slug'] = artistSlug;
    dataMap['view_count'] = viewCount;
    dataMap['like_count'] = likeCount;
    dataMap['favorite_count'] = favoriteCount;
    dataMap['comment_count'] = commentCount;
    dataMap['duration'] = duration;
    dataMap['definition'] = definition;
    dataMap['caption'] = caption;
    dataMap['insert_dt'] = insertDt;
    return dataMap;
  }
}
