class Autogenerated {
  String? message;
  Data? data;

  Autogenerated({this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    data = json['data'] != null ? Data.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['message'] = message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  String? youtubeViewsCount;
  String? youtubeLikesCount;
  String? youtubeFavoritesCount;
  String? youtubeCommentCount;
  String? youtubeVideoPublishDate;

  Data({
    this.youtubeViewsCount,
    this.youtubeLikesCount,
    this.youtubeFavoritesCount,
    this.youtubeCommentCount,
    this.youtubeVideoPublishDate,
  });

  Data.fromJson(Map<String, dynamic> json) {
    youtubeViewsCount = json['youtube_views_count'];
    youtubeLikesCount = json['youtube_likes_count'];
    youtubeFavoritesCount = json['youtube_favorites_count'];
    youtubeCommentCount = json['youtube_comment_count'];
    youtubeVideoPublishDate = json['youtube_video_publish_date'];
  }

  Map<String, dynamic> toJson() {
    return {
      'youtube_views_count': youtubeViewsCount,
      'youtube_likes_count': youtubeLikesCount,
      'youtube_favorites_count': youtubeFavoritesCount,
      'youtube_comment_count': youtubeCommentCount,
      'youtube_video_publish_date': youtubeVideoPublishDate,
    };
  }
}
