class Autogenerated {
  int? success;
  String? message;
  int? currentRecord;
  List<Data>? data;

  Autogenerated({this.success, this.message, this.currentRecord, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    currentRecord = json['currentRecord'];
    if (json['data'] != null) {
      data = List<Data>.from(json['data'].map((v) => Data.fromJson(v)));
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> jsonData = {};
    jsonData['success'] = this.success;
    jsonData['message'] = this.message;
    jsonData['currentRecord'] = this.currentRecord;
    if (this.data != null) {
      jsonData['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return jsonData;
  }
}

class Data {
  int? artistId;
  String? artistName;
  String? smallImg;
  String? mediumImg;
  String? largeImg;
  String? slug;
  String? channelId;
  String? insertDt;
  int? maxViewCount;

  Data({
    this.artistId,
    this.artistName,
    this.smallImg,
    this.mediumImg,
    this.largeImg,
    this.slug,
    this.channelId,
    this.insertDt,
    this.maxViewCount,
  });

  Data.fromJson(Map<String, dynamic> json) {
    artistId = json['artist_id'];
    artistName = json['artist_name'];
    smallImg = json['small_img'];
    mediumImg = json['medium_img'];
    largeImg = json['large_img'];
    slug = json['slug'];
    channelId = json['channel_id'];
    insertDt = json['insert_dt'];
    maxViewCount = json['max_view_count'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> jsonData = {};
    jsonData['artist_id'] = this.artistId;
    jsonData['artist_name'] = this.artistName;
    jsonData['small_img'] = this.smallImg;
    jsonData['medium_img'] = this.mediumImg;
    jsonData['large_img'] = this.largeImg;
    jsonData['slug'] = this.slug;
    jsonData['channel_id'] = this.channelId;
    jsonData['insert_dt'] = this.insertDt;
    jsonData['max_view_count'] = this.maxViewCount;
    return jsonData;
  }
}
