class Autogenerated {
  String? message;
  Data? data;

  Autogenerated({this.message, this.data});

  factory Autogenerated.fromJson(Map<String, dynamic> json) {
    return Autogenerated(
      message: json['message'],
      data: json['data'] != null ? Data.fromJson(json['data']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class Data {
  int? videoStaticsId;
  String? videoStaticsUuid;
  String? videoLink;
  int? youtubeViewsCount;
  int? youtubeLikesCount;
  int? youtubeFavoritesCount;
  int? youtubeCommentCount;
  String? youtubeVideoPublishDate;
  String? status;
  String? createdByUuid;
  String? createdByName;
  String? modifiedByUuid;
  String? modifiedByName;
  String? createTs;
  String? insertTs;

  Data({
    this.videoStaticsId,
    this.videoStaticsUuid,
    this.videoLink,
    this.youtubeViewsCount,
    this.youtubeLikesCount,
    this.youtubeFavoritesCount,
    this.youtubeCommentCount,
    this.youtubeVideoPublishDate,
    this.status,
    this.createdByUuid,
    this.createdByName,
    this.modifiedByUuid,
    this.modifiedByName,
    this.createTs,
    this.insertTs,
  });

  factory Data.fromJson(Map<String, dynamic> json) {
    return Data(
      videoStaticsId: json['video_statics_id'],
      videoStaticsUuid: json['video_statics_uuid'],
      videoLink: json['video_link'],
      youtubeViewsCount: json['youtube_views_count'],
      youtubeLikesCount: json['youtube_likes_count'],
      youtubeFavoritesCount: json['youtube_favorites_count'],
      youtubeCommentCount: json['youtube_comment_count'],
      youtubeVideoPublishDate: json['youtube_video_publish_date'],
      status: json['status'],
      createdByUuid: json['created_by_uuid'],
      createdByName: json['created_by_name'],
      modifiedByUuid: json['modified_by_uuid'],
      modifiedByName: json['modified_by_name'],
      createTs: json['create_ts'],
      insertTs: json['insert_ts'],
    );
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = {};
    data['video_statics_id'] = this.videoStaticsId;
    data['video_statics_uuid'] = this.videoStaticsUuid;
    data['video_link'] = this.videoLink;
    data['youtube_views_count'] = this.youtubeViewsCount;
    data['youtube_likes_count'] = this.youtubeLikesCount;
    data['youtube_favorites_count'] = this.youtubeFavoritesCount;
    data['youtube_comment_count'] = this.youtubeCommentCount;
    data['youtube_video_publish_date'] = this.youtubeVideoPublishDate;
    data['status'] = this.status;
    data['created_by_uuid'] = this.createdByUuid;
    data['created_by_name'] = this.createdByName;
    data['modified_by_uuid'] = this.modifiedByUuid;
    data['modified_by_name'] = this.modifiedByName;
    data['create_ts'] = this.createTs;
    data['insert_ts'] = this.insertTs;
    return data;
  }
}
