class Autogenerated {
  String? message;
  int? totalRecords;
  int? currentRecords;
  List<Data>? data;

  Autogenerated(
      {this.message, this.totalRecords, this.currentRecords, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    totalRecords = json['totalRecords'];
    currentRecords = json['currentRecords'];
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['message'] = message;
    data['totalRecords'] = totalRecords;
    data['currentRecords'] = currentRecords;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Data {
  int? artistId;
  String? channelId;
  String? channelName;
  String? artistUuid;
  String? artistName;
  String? artistSmallImg;
  String? artistMediumImg;
  String? artistLargeImg;

  String? artistSlug;
  String? status;
  String? createdByUuid;
  String? createdByName;
  String? modifiedByUuid;
  String? modifiedByName;
  String? createTs;

  Data(
      {this.artistId,
      this.channelId,
      this.channelName,
      this.artistUuid,
      this.artistName,
      this.artistSmallImg,
      this.artistMediumImg,
      this.artistLargeImg,
      this.artistSlug,
      this.status,
      this.createdByUuid,
      this.createdByName,
      this.modifiedByUuid,
      this.modifiedByName,
      this.createTs});

  Data.fromJson(Map<String, dynamic> json) {
    artistId = json['artist_id'];
    channelId = json['channel_id'];
    channelName = json['channel_name']??"";
    artistUuid = json['artist_uuid']??"";
    artistName = json['artist_name']??"";
    artistSmallImg = json['artist_small_img']??"";
    artistMediumImg = json['artist_medium_img']??json['artist_small_img'];
    artistLargeImg = json['artist_large_img']??json['artist_medium_img'];

    artistSlug = json['artist_slug'];
    status = json['status'];
    createdByUuid = json['created_by_uuid'];
    createdByName = json['created_by_name'];
    modifiedByUuid = json['modified_by_uuid'];
    modifiedByName = json['modified_by_name'];
    createTs = json['create_ts'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['artist_id'] = artistId;
    data['channel_id'] = channelId;
    data['channel_name'] = channelName;
    data['artist_uuid'] = artistUuid;
    data['artist_name'] = artistName;
    data['artist_small_img'] = artistSmallImg;
    data['artist_medium_img'] = artistMediumImg;
    data['artist_large_img'] = artistLargeImg;

    data['artist_slug'] = artistSlug;
    data['status'] = status;
    data['created_by_uuid'] = createdByUuid;
    data['created_by_name'] = createdByName;
    data['modified_by_uuid'] = modifiedByUuid;
    data['modified_by_name'] = modifiedByName;
    data['create_ts'] = createTs;
    return data;
  }
}
