/// message : "Artist"
/// totalRecords : 1
/// currentRecords : 1
/// data : [{"artist_wiki_bio_uuid":"7775788a-6e12-45c6-9d46-29fa1f21b6d5","artist_id":84,"artist_bio":"I’m Appurv Gupta aka GuptaJi, Host of The Kaafi Wild Hai Show : India Ka sable Wild Podcast, and I’m super happy you found us on youtube. <br />\nAfter entertaining you with my comedy for the past 11 years, I started this podcast to entertain you even more with fun, interesting and light hearted conversations. \n\nIn the span of 11 years of my career I had the privilege of meeting some amazing people and had some great conversations that have shaped me as a person. The purpose to start this podcast is to now share all those meaningful insights with my audience but keeping it chill at the same time.\n\nMy intent is to create a podcast that you can tune into at the end of an exhausting day to relax and unwind, just like you would do with a friend. Hope you enjoy listening to this podcast as much as I enjoy recording it.\n","artist_father_name":null,"artist_mother_name":null,"artist_dob":null,"artist_birth_place":null,"artist_city":null,"artist_schooling":null,"artist_and_college":null,"artist_relationship_status":null,"artist_genre":null,"artist_insta_handle":null,"artist_facebook_handle":null,"additional_info":null,"status":"ACTIVE","created_by_uuid":"09d6fa62-a354-407e-8fa2-83ae3821e617","created_by_name":"Arpit Awasthi","modified_by_uuid":"09d6fa62-a354-407e-8fa2-83ae3821e617","modified_by_name":"Arpit Awasthi","create_ts":"2024-10-16T09:09:20.000Z"}]

class Autogenerated {
  Autogenerated({
      String? message,
      num? totalRecords,
      num? currentRecords,
      List<Data>? data,}){
    _message = message;
    _totalRecords = totalRecords;
    _currentRecords = currentRecords;
    _data = data;
}

  Autogenerated.fromJson(dynamic json) {
    _message = json['message'];
    _totalRecords = json['totalRecords'];
    _currentRecords = json['currentRecords'];
    if (json['data'] != null) {
      _data = [];
      json['data'].forEach((v) {
        _data?.add(Data.fromJson(v));
      });
    }
  }
  String? _message;
  num? _totalRecords;
  num? _currentRecords;
  List<Data>? _data;
  Autogenerated copyWith({  String? message,
  num? totalRecords,
  num? currentRecords,
  List<Data>? data,
}) => Autogenerated(  message: message ?? _message,
  totalRecords: totalRecords ?? _totalRecords,
  currentRecords: currentRecords ?? _currentRecords,
  data: data ?? _data,
);
  String? get message => _message;
  num? get totalRecords => _totalRecords;
  num? get currentRecords => _currentRecords;
  List<Data>? get data => _data;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['message'] = _message;
    map['totalRecords'] = _totalRecords;
    map['currentRecords'] = _currentRecords;
    if (_data != null) {
      map['data'] = _data?.map((v) => v.toJson()).toList();
    }
    return map;
  }

}

/// artist_wiki_bio_uuid : "7775788a-6e12-45c6-9d46-29fa1f21b6d5"
/// artist_id : 84
/// artist_bio : "I’m Appurv Gupta aka GuptaJi, Host of The Kaafi Wild Hai Show : India Ka sable Wild Podcast, and I’m super happy you found us on youtube. <br />\nAfter entertaining you with my comedy for the past 11 years, I started this podcast to entertain you even more with fun, interesting and light hearted conversations. \n\nIn the span of 11 years of my career I had the privilege of meeting some amazing people and had some great conversations that have shaped me as a person. The purpose to start this podcast is to now share all those meaningful insights with my audience but keeping it chill at the same time.\n\nMy intent is to create a podcast that you can tune into at the end of an exhausting day to relax and unwind, just like you would do with a friend. Hope you enjoy listening to this podcast as much as I enjoy recording it.\n"
/// artist_father_name : null
/// artist_mother_name : null
/// artist_dob : null
/// artist_birth_place : null
/// artist_city : null
/// artist_schooling : null
/// artist_and_college : null
/// artist_relationship_status : null
/// artist_genre : null
/// artist_insta_handle : null
/// artist_facebook_handle : null
/// additional_info : null
/// status : "ACTIVE"
/// created_by_uuid : "09d6fa62-a354-407e-8fa2-83ae3821e617"
/// created_by_name : "Arpit Awasthi"
/// modified_by_uuid : "09d6fa62-a354-407e-8fa2-83ae3821e617"
/// modified_by_name : "Arpit Awasthi"
/// create_ts : "2024-10-16T09:09:20.000Z"

class Data {
  Data({
      String? artistWikiBioUuid,
      num? artistId,
      String? artistBio,
      dynamic artistFatherName,
      dynamic artistMotherName,
      dynamic artistDob,
      dynamic artistBirthPlace,
      dynamic artistCity,
      dynamic artistSchooling,
      dynamic artistAndCollege,
      dynamic artistRelationshipStatus,
      dynamic artistGenre,
      dynamic artistInstaHandle,
      dynamic artistFacebookHandle,
      dynamic additionalInfo,
      String? status,
      String? createdByUuid,
      String? createdByName,
      String? modifiedByUuid,
      String? modifiedByName,
      String? createTs,}){
    _artistWikiBioUuid = artistWikiBioUuid;
    _artistId = artistId;
    _artistBio = artistBio;
    _artistFatherName = artistFatherName;
    _artistMotherName = artistMotherName;
    _artistDob = artistDob;
    _artistBirthPlace = artistBirthPlace;
    _artistCity = artistCity;
    _artistSchooling = artistSchooling;
    _artistAndCollege = artistAndCollege;
    _artistRelationshipStatus = artistRelationshipStatus;
    _artistGenre = artistGenre;
    _artistInstaHandle = artistInstaHandle;
    _artistFacebookHandle = artistFacebookHandle;
    _additionalInfo = additionalInfo;
    _status = status;
    _createdByUuid = createdByUuid;
    _createdByName = createdByName;
    _modifiedByUuid = modifiedByUuid;
    _modifiedByName = modifiedByName;
    _createTs = createTs;
}

  Data.fromJson(dynamic json) {
    _artistWikiBioUuid = json['artist_wiki_bio_uuid'];
    _artistId = json['artist_id'];
    _artistBio = json['artist_bio']??"";
    _artistFatherName = json['artist_father_name']??"";
    _artistMotherName = json['artist_mother_name']??"";
    _artistDob = json['artist_dob']??"";
    _artistBirthPlace = json['artist_birth_place']??"";
    _artistCity = json['artist_city']??"";
    _artistSchooling = json['artist_schooling']??"";
    _artistAndCollege = json['artist_and_college']??"";
    _artistRelationshipStatus = json['artist_relationship_status']??"";
    _artistGenre = json['artist_genre']??"";
    _artistInstaHandle = json['artist_insta_handle']??'';
    _artistFacebookHandle = json['artist_facebook_handle']??"";
    _additionalInfo = json['additional_info']??"";
    _status = json['status']??"";
    _createdByUuid = json['created_by_uuid']??"";
    _createdByName = json['created_by_name']??"";
    _modifiedByUuid = json['modified_by_uuid']??"";
    _modifiedByName = json['modified_by_name']??"";
    _createTs = json['create_ts'];
  }
  String? _artistWikiBioUuid;
  num? _artistId;
  String? _artistBio;
  dynamic _artistFatherName;
  dynamic _artistMotherName;
  dynamic _artistDob;
  dynamic _artistBirthPlace;
  dynamic _artistCity;
  dynamic _artistSchooling;
  dynamic _artistAndCollege;
  dynamic _artistRelationshipStatus;
  dynamic _artistGenre;
  dynamic _artistInstaHandle;
  dynamic _artistFacebookHandle;
  dynamic _additionalInfo;
  String? _status;
  String? _createdByUuid;
  String? _createdByName;
  String? _modifiedByUuid;
  String? _modifiedByName;
  String? _createTs;
Data copyWith({  String? artistWikiBioUuid,
  num? artistId,
  String? artistBio,
  dynamic artistFatherName,
  dynamic artistMotherName,
  dynamic artistDob,
  dynamic artistBirthPlace,
  dynamic artistCity,
  dynamic artistSchooling,
  dynamic artistAndCollege,
  dynamic artistRelationshipStatus,
  dynamic artistGenre,
  dynamic artistInstaHandle,
  dynamic artistFacebookHandle,
  dynamic additionalInfo,
  String? status,
  String? createdByUuid,
  String? createdByName,
  String? modifiedByUuid,
  String? modifiedByName,
  String? createTs,
}) => Data(  artistWikiBioUuid: artistWikiBioUuid ?? _artistWikiBioUuid,
  artistId: artistId ?? _artistId,
  artistBio: artistBio ?? _artistBio,
  artistFatherName: artistFatherName ?? _artistFatherName,
  artistMotherName: artistMotherName ?? _artistMotherName,
  artistDob: artistDob ?? _artistDob,
  artistBirthPlace: artistBirthPlace ?? _artistBirthPlace,
  artistCity: artistCity ?? _artistCity,
  artistSchooling: artistSchooling ?? _artistSchooling,
  artistAndCollege: artistAndCollege ?? _artistAndCollege,
  artistRelationshipStatus: artistRelationshipStatus ?? _artistRelationshipStatus,
  artistGenre: artistGenre ?? _artistGenre,
  artistInstaHandle: artistInstaHandle ?? _artistInstaHandle,
  artistFacebookHandle: artistFacebookHandle ?? _artistFacebookHandle,
  additionalInfo: additionalInfo ?? _additionalInfo,
  status: status ?? _status,
  createdByUuid: createdByUuid ?? _createdByUuid,
  createdByName: createdByName ?? _createdByName,
  modifiedByUuid: modifiedByUuid ?? _modifiedByUuid,
  modifiedByName: modifiedByName ?? _modifiedByName,
  createTs: createTs ?? _createTs,
);
  String? get artistWikiBioUuid => _artistWikiBioUuid;
  num? get artistId => _artistId;
  String? get artistBio => _artistBio;
  dynamic get artistFatherName => _artistFatherName;
  dynamic get artistMotherName => _artistMotherName;
  dynamic get artistDob => _artistDob;
  dynamic get artistBirthPlace => _artistBirthPlace;
  dynamic get artistCity => _artistCity;
  dynamic get artistSchooling => _artistSchooling;
  dynamic get artistAndCollege => _artistAndCollege;
  dynamic get artistRelationshipStatus => _artistRelationshipStatus;
  dynamic get artistGenre => _artistGenre;
  dynamic get artistInstaHandle => _artistInstaHandle;
  dynamic get artistFacebookHandle => _artistFacebookHandle;
  dynamic get additionalInfo => _additionalInfo;
  String? get status => _status;
  String? get createdByUuid => _createdByUuid;
  String? get createdByName => _createdByName;
  String? get modifiedByUuid => _modifiedByUuid;
  String? get modifiedByName => _modifiedByName;
  String? get createTs => _createTs;

  Map<String, dynamic> toJson() {
    final map = <String, dynamic>{};
    map['artist_wiki_bio_uuid'] = _artistWikiBioUuid;
    map['artist_id'] = _artistId;
    map['artist_bio'] = _artistBio;
    map['artist_father_name'] = _artistFatherName;
    map['artist_mother_name'] = _artistMotherName;
    map['artist_dob'] = _artistDob;
    map['artist_birth_place'] = _artistBirthPlace;
    map['artist_city'] = _artistCity;
    map['artist_schooling'] = _artistSchooling;
    map['artist_and_college'] = _artistAndCollege;
    map['artist_relationship_status'] = _artistRelationshipStatus;
    map['artist_genre'] = _artistGenre;
    map['artist_insta_handle'] = _artistInstaHandle;
    map['artist_facebook_handle'] = _artistFacebookHandle;
    map['additional_info'] = _additionalInfo;
    map['status'] = _status;
    map['created_by_uuid'] = _createdByUuid;
    map['created_by_name'] = _createdByName;
    map['modified_by_uuid'] = _modifiedByUuid;
    map['modified_by_name'] = _modifiedByName;
    map['create_ts'] = _createTs;
    return map;
  }

}