class Autogenerated {
  int? success;
  String? message;
  HomePageData? data;

  Autogenerated({this.success, this.message, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message'];
    data = json['data'] != null ? HomePageData.fromJson(json['data']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['success'] = this.success;
    data['message'] = this.message;
    if (this.data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}

class HomePageData {
  List<Slider>? slider;
  List<PageContent>? pageContent;
  List<HomePageFooter>? homePageFooter;

  HomePageData({this.slider, this.pageContent, this.homePageFooter});

  HomePageData.fromJson(Map<String, dynamic> json) {
    if (json['slider'] != null) {
      slider = <Slider>[];
      json['slider'].forEach((v) {
        slider!.add(Slider.fromJson(v));
      });
    }
    if (json['pageContent'] != null) {
      pageContent = <PageContent>[];
      json['pageContent'].forEach((v) {
        pageContent!.add(PageContent.fromJson(v));
      });
    }
    if (json['homePageFooter'] != null) {
      homePageFooter = <HomePageFooter>[];
      json['homePageFooter'].forEach((v) {
        homePageFooter!.add(HomePageFooter.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.slider != null) {
      data['slider'] = this.slider!.map((v) => v.toJson()).toList();
    }
    if (this.pageContent != null) {
      data['pageContent'] = this.pageContent!.map((v) => v.toJson()).toList();
    }
    if (this.homePageFooter != null) {
      data['homePageFooter'] =
          this.homePageFooter!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Slider {
  int? id;
  String? title;
  String? image;
  String? slug;

  Slider({this.id, this.title, this.image, this.slug});

  Slider.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    image = json['image'];
    slug = json['slug'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['image'] = this.image;
    data['slug'] = this.slug;
    return data;
  }
}

class PageContent {
  String? title;
  List<PageContentData>? data;

  PageContent({this.title, this.data});

  PageContent.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    if (json['data'] != null) {
      data = <PageContentData>[];
      json['data'].forEach((v) {
        data!.add(PageContentData.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['title'] = this.title;
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class PageContentData {
  int? id;
  String? title;
  String? image;
  String? slug;
  String? category;

  PageContentData({this.id, this.title, this.image, this.slug, this.category});

  PageContentData.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    image = json['image'];
    slug = json['slug'];
    category = json['category'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['image'] = this.image;
    data['slug'] = this.slug;
    data['category'] = this.category;
    return data;
  }
}

class HomePageFooter {
  String? url;
  String? label;

  HomePageFooter({this.url, this.label});

  HomePageFooter.fromJson(Map<String, dynamic> json) {
    url = json['url'];
    label = json['label'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['url'] = this.url;
    data['label'] = this.label;
    return data;
  }
}
